name: fmt
on: pull_request

jobs:
  cargo-fmt:
    runs-on: [matterlabs-ci-runner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          profile: minimal
          override: true
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
